site_name: discovery v0.0.1+00000000
site_url: http://byron.github.io/google-apis-rs/google-discovery1-cli
site_description: Write integrating applications with bcore

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/discovery1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['apis_get-rest.md', 'Apis', 'Get Rest']
- ['apis_list.md', 'Apis', 'List']

theme: readthedocs

copyright: Copyright &copy; 2015, `Sebastian Thiel`

