site_name: container v0.3.5+20160321
site_url: http://byron.github.io/google-apis-rs/google-container1-cli
site_description: Write integrating applications with bcore

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/container1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['projects_zones-clusters-create.md', 'Projects', 'Zones Clusters Create']
- ['projects_zones-clusters-delete.md', 'Projects', 'Zones Clusters Delete']
- ['projects_zones-clusters-get.md', 'Projects', 'Zones Clusters Get']
- ['projects_zones-clusters-list.md', 'Projects', 'Zones Clusters List']
- ['projects_zones-clusters-update.md', 'Projects', 'Zones Clusters Update']
- ['projects_zones-get-serverconfig.md', 'Projects', 'Zones Get Serverconfig']
- ['projects_zones-operations-get.md', 'Projects', 'Zones Operations Get']
- ['projects_zones-operations-list.md', 'Projects', 'Zones Operations List']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

