site_name: Shopping Content v0.3.6+20160331
site_url: http://byron.github.io/google-apis-rs/google-content2_sandbox-cli
site_description: Write integrating applications with bcore

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/content2_sandbox-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['orders_acknowledge.md', 'Orders', 'Acknowledge']
- ['orders_advancetestorder.md', 'Orders', 'Advancetestorder']
- ['orders_cancel.md', 'Orders', 'Cancel']
- ['orders_cancellineitem.md', 'Orders', 'Cancellineitem']
- ['orders_createtestorder.md', 'Orders', 'Createtestorder']
- ['orders_custombatch.md', 'Orders', 'Custombatch']
- ['orders_get.md', 'Orders', 'Get']
- ['orders_getbymerchantorderid.md', 'Orders', 'Getbymerchantorderid']
- ['orders_gettestordertemplate.md', 'Orders', 'Gettestordertemplate']
- ['orders_list.md', 'Orders', 'List']
- ['orders_refund.md', 'Orders', 'Refund']
- ['orders_returnlineitem.md', 'Orders', 'Returnlineitem']
- ['orders_shiplineitems.md', 'Orders', 'Shiplineitems']
- ['orders_updatemerchantorderid.md', 'Orders', 'Updatemerchantorderid']
- ['orders_updateshipment.md', 'Orders', 'Updateshipment']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

