language: rust
os:
  - linux
  - osx
rust:
  - stable
  - nightly
script:
  - make gen-all-cli cargo-api ARGS=test
  - make cargo-api ARGS=doc
  - "if [[ $TRAVIS_RUST_VERSION = nightly ]]; then cargo test; fi"
env:
  global:
    secure: Plj5DqAQX/4+KPM+nOAZ2sCbGIsoSrHo1YggfesQnU7paR734XO/4IayWnsNO/3q6bDi4GIcn56RUZAD3xBJJBNLia2CYIickIIYORRqLWbLdbzQaxBbD670ahtzEuUSFJTRKURPwFteAnsWYgNMNzwXOVNwLS5IUBqWTcS+N0g=
