# DO NOT PUBLISH
# This library is just to try out the code that should ultimately go into the code generator !
[package]

name = "cmn"
version = "0.0.1"
authors = ["Sebastian Thiel <byronimo@gmail.com>"]
description = "A library to facilitate interacting with your youtube account"
repository = "https://github.com/Byron/google-apis-rs"
license = "MIT"
keywords = ["youtube", "google", "protocol", "not-for-use"]

[lib]
# The common code, used by all generated implementations
name = "cmn"
path = "src/rust/lib.rs"

[dependencies]
hyper = "*"
mime = "*"
rustc-serialize = "*"
yup-oauth2 = "*"
serde = "*"
serde_macros = "*"

[dev-dependencies]
yup-hyper-mock = "*"
