[package]

name = "youtube"
version = "0.0.1"
authors = ["Sebastian Thiel <byronimo@gmail.com>"]
description = "A library to facilitate interacting with your youtube account"
repository = "https://github.com/Byron/youtube-rs"
license = "MIT"
keywords = ["youtube", "google", "protocol"]

[dependencies]
hyper = "*"
