site_name: QPX Express v0.3.2+20140321
site_url: http://byron.github.io/google-apis-rs/google-qpxexpress1-cli
site_description: Write integrating applications with bcore

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/qpxexpress1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['trips_search.md', 'Trips', 'Search']

theme: readthedocs

copyright: Copyright &copy; 2015, `Sebastian Thiel`

