site_name: monitoring v1.0.0+20160425
site_url: http://byron.github.io/google-apis-rs/google-monitoring3-cli
site_description: Write integrating applications with bcore

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/monitoring3-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['projects_collectd-time-series-create.md', 'Projects', 'Collectd Time Series Create']
- ['projects_groups-create.md', 'Projects', 'Groups Create']
- ['projects_groups-delete.md', 'Projects', 'Groups Delete']
- ['projects_groups-get.md', 'Projects', 'Groups Get']
- ['projects_groups-list.md', 'Projects', 'Groups List']
- ['projects_groups-members-list.md', 'Projects', 'Groups Members List']
- ['projects_groups-update.md', 'Projects', 'Groups Update']
- ['projects_metric-descriptors-create.md', 'Projects', 'Metric Descriptors Create']
- ['projects_metric-descriptors-delete.md', 'Projects', 'Metric Descriptors Delete']
- ['projects_metric-descriptors-get.md', 'Projects', 'Metric Descriptors Get']
- ['projects_metric-descriptors-list.md', 'Projects', 'Metric Descriptors List']
- ['projects_monitored-resource-descriptors-get.md', 'Projects', 'Monitored Resource Descriptors Get']
- ['projects_monitored-resource-descriptors-list.md', 'Projects', 'Monitored Resource Descriptors List']
- ['projects_time-series-create.md', 'Projects', 'Time Series Create']
- ['projects_time-series-list.md', 'Projects', 'Time Series List']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

