site_name: dns v1.0.6+20170512
site_url: http://byron.github.io/google-apis-rs/google-dns1-cli
site_description: A complete library to interact with dns (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/dns1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['changes_create.md', 'Changes', 'Create']
- ['changes_get.md', 'Changes', 'Get']
- ['changes_list.md', 'Changes', 'List']
- ['managed-zones_create.md', 'Managed Zones', 'Create']
- ['managed-zones_delete.md', 'Managed Zones', 'Delete']
- ['managed-zones_get.md', 'Managed Zones', 'Get']
- ['managed-zones_list.md', 'Managed Zones', 'List']
- ['projects_get.md', 'Projects', 'Get']
- ['resource-record-sets_list.md', 'Resource Record Sets', 'List']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

