site_name: customsearch v1.0.5+20160411
site_url: http://byron.github.io/google-apis-rs/google-customsearch1-cli
site_description: A complete library to interact with customsearch (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/customsearch1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['cse_list.md', 'Cse', 'List']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

