site_name: Tool Results v0.3.5+20160408
site_url: http://byron.github.io/google-apis-rs/google-toolresults1_beta3-cli
site_description: Write integrating applications with bcore

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/toolresults1_beta3-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['projects_get-settings.md', 'Projects', 'Get Settings']
- ['projects_histories-create.md', 'Projects', 'Histories Create']
- ['projects_histories-executions-create.md', 'Projects', 'Histories Executions Create']
- ['projects_histories-executions-get.md', 'Projects', 'Histories Executions Get']
- ['projects_histories-executions-list.md', 'Projects', 'Histories Executions List']
- ['projects_histories-executions-patch.md', 'Projects', 'Histories Executions Patch']
- ['projects_histories-executions-steps-create.md', 'Projects', 'Histories Executions Steps Create']
- ['projects_histories-executions-steps-get.md', 'Projects', 'Histories Executions Steps Get']
- ['projects_histories-executions-steps-list.md', 'Projects', 'Histories Executions Steps List']
- ['projects_histories-executions-steps-patch.md', 'Projects', 'Histories Executions Steps Patch']
- ['projects_histories-executions-steps-publish-xunit-xml-files.md', 'Projects', 'Histories Executions Steps Publish Xunit Xml Files']
- ['projects_histories-executions-steps-thumbnails-list.md', 'Projects', 'Histories Executions Steps Thumbnails List']
- ['projects_histories-get.md', 'Projects', 'Histories Get']
- ['projects_histories-list.md', 'Projects', 'Histories List']
- ['projects_initialize-settings.md', 'Projects', 'Initialize Settings']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

