site_name: datastore v0.1.0+20150402
site_url: http://byron.github.io/google-apis-rs/google-datastore1_beta2-cli
site_description: Write integrating applications with bcore

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/datastore1_beta2-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['datasets_allocate-ids.md', 'Datasets', 'Allocate Ids']
- ['datasets_begin-transaction.md', 'Datasets', 'Begin Transaction']
- ['datasets_commit.md', 'Datasets', 'Commit']
- ['datasets_lookup.md', 'Datasets', 'Lookup']
- ['datasets_rollback.md', 'Datasets', 'Rollback']
- ['datasets_run-query.md', 'Datasets', 'Run Query']

theme: readthedocs

copyright: Copyright &copy; 2015, `Sebastian Thiel`

