site_name: dataproc v1.0.2+20161102
site_url: http://byron.github.io/google-apis-rs/google-dataproc1-cli
site_description: A complete library to interact with dataproc (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/dataproc1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['projects_regions-clusters-create.md', 'Projects', 'Regions Clusters Create']
- ['projects_regions-clusters-delete.md', 'Projects', 'Regions Clusters Delete']
- ['projects_regions-clusters-diagnose.md', 'Projects', 'Regions Clusters Diagnose']
- ['projects_regions-clusters-get.md', 'Projects', 'Regions Clusters Get']
- ['projects_regions-clusters-list.md', 'Projects', 'Regions Clusters List']
- ['projects_regions-clusters-patch.md', 'Projects', 'Regions Clusters Patch']
- ['projects_regions-jobs-cancel.md', 'Projects', 'Regions Jobs Cancel']
- ['projects_regions-jobs-delete.md', 'Projects', 'Regions Jobs Delete']
- ['projects_regions-jobs-get.md', 'Projects', 'Regions Jobs Get']
- ['projects_regions-jobs-list.md', 'Projects', 'Regions Jobs List']
- ['projects_regions-jobs-submit.md', 'Projects', 'Regions Jobs Submit']
- ['projects_regions-operations-cancel.md', 'Projects', 'Regions Operations Cancel']
- ['projects_regions-operations-delete.md', 'Projects', 'Regions Operations Delete']
- ['projects_regions-operations-get.md', 'Projects', 'Regions Operations Get']
- ['projects_regions-operations-list.md', 'Projects', 'Regions Operations List']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

