site_name: webfonts v0.2.0+20140210
site_url: http://byron.github.io/google-apis-rs/google-webfonts1-cli
site_description: Write integrating applications with bcore

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/webfonts1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['webfonts_list.md', 'Webfonts', 'List']

theme: readthedocs

copyright: Copyright &copy; 2015, `Sebastian Thiel`

