site_name: TPU v1.0.7+20171121
site_url: http://byron.github.io/google-apis-rs/google-tpu1_alpha1-cli
site_description: A complete library to interact with TPU (protocol v1alpha1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/tpu1_alpha1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['projects_locations-get.md', 'Projects', 'Locations Get']
- ['projects_locations-list.md', 'Projects', 'Locations List']
- ['projects_locations-nodes-create.md', 'Projects', 'Locations Nodes Create']
- ['projects_locations-nodes-delete.md', 'Projects', 'Locations Nodes Delete']
- ['projects_locations-nodes-get.md', 'Projects', 'Locations Nodes Get']
- ['projects_locations-nodes-list.md', 'Projects', 'Locations Nodes List']
- ['projects_locations-nodes-reimage.md', 'Projects', 'Locations Nodes Reimage']
- ['projects_locations-nodes-reset.md', 'Projects', 'Locations Nodes Reset']
- ['projects_locations-operations-cancel.md', 'Projects', 'Locations Operations Cancel']
- ['projects_locations-operations-delete.md', 'Projects', 'Locations Operations Delete']
- ['projects_locations-operations-get.md', 'Projects', 'Locations Operations Get']
- ['projects_locations-operations-list.md', 'Projects', 'Locations Operations List']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

