site_name: logging v0.3.2+20151007
site_url: http://byron.github.io/google-apis-rs/google-logging2_beta1-cli
site_description: Write integrating applications with bcore

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/logging2_beta1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']

theme: readthedocs

copyright: Copyright &copy; 2015, `Sebastian Thiel`

