site_name: container v0.1.0+20150420
site_url: http://byron.github.io/google-apis-rs/google-container1_beta1-cli
site_description: Write integrating applications with bcore

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/container1_beta1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['projects_clusters-list.md', 'Projects', 'Clusters List']
- ['projects_operations-list.md', 'Projects', 'Operations List']
- ['projects_zones-clusters-create.md', 'Projects', 'Zones Clusters Create']
- ['projects_zones-clusters-delete.md', 'Projects', 'Zones Clusters Delete']
- ['projects_zones-clusters-get.md', 'Projects', 'Zones Clusters Get']
- ['projects_zones-clusters-list.md', 'Projects', 'Zones Clusters List']
- ['projects_zones-operations-get.md', 'Projects', 'Zones Operations Get']
- ['projects_zones-operations-list.md', 'Projects', 'Zones Operations List']
- ['projects_zones-tokens-get.md', 'Projects', 'Zones Tokens Get']

theme: readthedocs

copyright: Copyright &copy; 2015, `Sebastian Thiel`

