site_name: People Service v1.0.5+20170518
site_url: http://byron.github.io/google-apis-rs/google-people1-cli
site_description: A complete library to interact with People Service (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/people1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['people_connections-list.md', 'People', 'Connections List']
- ['people_get.md', 'People', 'Get']
- ['people_get-batch-get.md', 'People', 'Get Batch Get']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

