site_name: deploymentmanager v0.0.1+20150303
site_url: http://byron.github.io/google-apis-rs/google-deploymentmanager2_beta1-cli
site_description: Write integrating applications with bcore

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/deploymentmanager2_beta1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['deployments_delete.md', 'Deployments', 'Delete']
- ['deployments_get.md', 'Deployments', 'Get']
- ['deployments_insert.md', 'Deployments', 'Insert']
- ['deployments_list.md', 'Deployments', 'List']
- ['manifests_get.md', 'Manifests', 'Get']
- ['manifests_list.md', 'Manifests', 'List']
- ['operations_get.md', 'Operations', 'Get']
- ['operations_list.md', 'Operations', 'List']
- ['resources_get.md', 'Resources', 'Get']
- ['resources_list.md', 'Resources', 'List']
- ['types_list.md', 'Types', 'List']

theme: readthedocs

copyright: Copyright &copy; 2015, `Sebastian Thiel`

