site_name: Tag Manager v0.3.0+20150526
site_url: http://byron.github.io/google-apis-rs/google-tagmanager1-cli
site_description: Write integrating applications with bcore

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/tagmanager1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['accounts_containers-create.md', 'Accounts', 'Containers Create']
- ['accounts_containers-delete.md', 'Accounts', 'Containers Delete']
- ['accounts_containers-get.md', 'Accounts', 'Containers Get']
- ['accounts_containers-list.md', 'Accounts', 'Containers List']
- ['accounts_containers-macros-create.md', 'Accounts', 'Containers Macros Create']
- ['accounts_containers-macros-delete.md', 'Accounts', 'Containers Macros Delete']
- ['accounts_containers-macros-get.md', 'Accounts', 'Containers Macros Get']
- ['accounts_containers-macros-list.md', 'Accounts', 'Containers Macros List']
- ['accounts_containers-macros-update.md', 'Accounts', 'Containers Macros Update']
- ['accounts_containers-rules-create.md', 'Accounts', 'Containers Rules Create']
- ['accounts_containers-rules-delete.md', 'Accounts', 'Containers Rules Delete']
- ['accounts_containers-rules-get.md', 'Accounts', 'Containers Rules Get']
- ['accounts_containers-rules-list.md', 'Accounts', 'Containers Rules List']
- ['accounts_containers-rules-update.md', 'Accounts', 'Containers Rules Update']
- ['accounts_containers-tags-create.md', 'Accounts', 'Containers Tags Create']
- ['accounts_containers-tags-delete.md', 'Accounts', 'Containers Tags Delete']
- ['accounts_containers-tags-get.md', 'Accounts', 'Containers Tags Get']
- ['accounts_containers-tags-list.md', 'Accounts', 'Containers Tags List']
- ['accounts_containers-tags-update.md', 'Accounts', 'Containers Tags Update']
- ['accounts_containers-triggers-create.md', 'Accounts', 'Containers Triggers Create']
- ['accounts_containers-triggers-delete.md', 'Accounts', 'Containers Triggers Delete']
- ['accounts_containers-triggers-get.md', 'Accounts', 'Containers Triggers Get']
- ['accounts_containers-triggers-list.md', 'Accounts', 'Containers Triggers List']
- ['accounts_containers-triggers-update.md', 'Accounts', 'Containers Triggers Update']
- ['accounts_containers-update.md', 'Accounts', 'Containers Update']
- ['accounts_containers-variables-create.md', 'Accounts', 'Containers Variables Create']
- ['accounts_containers-variables-delete.md', 'Accounts', 'Containers Variables Delete']
- ['accounts_containers-variables-get.md', 'Accounts', 'Containers Variables Get']
- ['accounts_containers-variables-list.md', 'Accounts', 'Containers Variables List']
- ['accounts_containers-variables-update.md', 'Accounts', 'Containers Variables Update']
- ['accounts_containers-versions-create.md', 'Accounts', 'Containers Versions Create']
- ['accounts_containers-versions-delete.md', 'Accounts', 'Containers Versions Delete']
- ['accounts_containers-versions-get.md', 'Accounts', 'Containers Versions Get']
- ['accounts_containers-versions-list.md', 'Accounts', 'Containers Versions List']
- ['accounts_containers-versions-publish.md', 'Accounts', 'Containers Versions Publish']
- ['accounts_containers-versions-restore.md', 'Accounts', 'Containers Versions Restore']
- ['accounts_containers-versions-undelete.md', 'Accounts', 'Containers Versions Undelete']
- ['accounts_containers-versions-update.md', 'Accounts', 'Containers Versions Update']
- ['accounts_get.md', 'Accounts', 'Get']
- ['accounts_list.md', 'Accounts', 'List']
- ['accounts_permissions-create.md', 'Accounts', 'Permissions Create']
- ['accounts_permissions-delete.md', 'Accounts', 'Permissions Delete']
- ['accounts_permissions-get.md', 'Accounts', 'Permissions Get']
- ['accounts_permissions-list.md', 'Accounts', 'Permissions List']
- ['accounts_permissions-update.md', 'Accounts', 'Permissions Update']
- ['accounts_update.md', 'Accounts', 'Update']

theme: readthedocs

copyright: Copyright &copy; 2015, `Sebastian Thiel`

