site_name: dataflow v0.0.1+20150401
site_url: http://byron.github.io/google-apis-rs/google-dataflow1_b4-cli
site_description: Write integrating applications with bcore

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/dataflow1_b4-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']

theme: readthedocs

copyright: Copyright &copy; 2015, `Sebastian Thiel`

