site_name: Cloud Machine Learning v1.0.2+20161212
site_url: http://byron.github.io/google-apis-rs/google-ml1_beta1-cli
site_description: A complete library to interact with Cloud Machine Learning (protocol v1beta1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/ml1_beta1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['projects_get-config.md', 'Projects', 'Get Config']
- ['projects_jobs-cancel.md', 'Projects', 'Jobs Cancel']
- ['projects_jobs-create.md', 'Projects', 'Jobs Create']
- ['projects_jobs-get.md', 'Projects', 'Jobs Get']
- ['projects_jobs-list.md', 'Projects', 'Jobs List']
- ['projects_models-create.md', 'Projects', 'Models Create']
- ['projects_models-delete.md', 'Projects', 'Models Delete']
- ['projects_models-get.md', 'Projects', 'Models Get']
- ['projects_models-list.md', 'Projects', 'Models List']
- ['projects_models-versions-create.md', 'Projects', 'Models Versions Create']
- ['projects_models-versions-delete.md', 'Projects', 'Models Versions Delete']
- ['projects_models-versions-get.md', 'Projects', 'Models Versions Get']
- ['projects_models-versions-list.md', 'Projects', 'Models Versions List']
- ['projects_models-versions-set-default.md', 'Projects', 'Models Versions Set Default']
- ['projects_operations-cancel.md', 'Projects', 'Operations Cancel']
- ['projects_operations-delete.md', 'Projects', 'Operations Delete']
- ['projects_operations-get.md', 'Projects', 'Operations Get']
- ['projects_operations-list.md', 'Projects', 'Operations List']
- ['projects_predict.md', 'Projects', 'Predict']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

