site_name: Street View Publish v1.0.6+20170925
site_url: http://byron.github.io/google-apis-rs/google-streetviewpublish1-cli
site_description: A complete library to interact with Street View Publish (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/streetviewpublish1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['photo_create.md', 'Photo', 'Create']
- ['photo_delete.md', 'Photo', 'Delete']
- ['photo_get.md', 'Photo', 'Get']
- ['photo_start-upload.md', 'Photo', 'Start Upload']
- ['photo_update.md', 'Photo', 'Update']
- ['photos_batch-delete.md', 'Photos', 'Batch Delete']
- ['photos_batch-get.md', 'Photos', 'Batch Get']
- ['photos_batch-update.md', 'Photos', 'Batch Update']
- ['photos_list.md', 'Photos', 'List']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

