site_name: kgsearch v0.3.6+20151215
site_url: http://byron.github.io/google-apis-rs/google-kgsearch1-cli
site_description: Write integrating applications with bcore

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/kgsearch1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['entities_search.md', 'Entities', 'Search']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

