site_name: logging v0.0.1+20150326
site_url: http://byron.github.io/google-apis-rs/google-logging1_beta3-cli
site_description: Write integrating applications with bcore

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/logging1_beta3-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['projects_log-services-indexes-list.md', 'Projects', 'Log Services Indexes List']
- ['projects_log-services-list.md', 'Projects', 'Log Services List']
- ['projects_log-services-sinks-create.md', 'Projects', 'Log Services Sinks Create']
- ['projects_log-services-sinks-delete.md', 'Projects', 'Log Services Sinks Delete']
- ['projects_log-services-sinks-get.md', 'Projects', 'Log Services Sinks Get']
- ['projects_log-services-sinks-list.md', 'Projects', 'Log Services Sinks List']
- ['projects_log-services-sinks-update.md', 'Projects', 'Log Services Sinks Update']
- ['projects_logs-delete.md', 'Projects', 'Logs Delete']
- ['projects_logs-entries-write.md', 'Projects', 'Logs Entries Write']
- ['projects_logs-list.md', 'Projects', 'Logs List']
- ['projects_logs-sinks-create.md', 'Projects', 'Logs Sinks Create']
- ['projects_logs-sinks-delete.md', 'Projects', 'Logs Sinks Delete']
- ['projects_logs-sinks-get.md', 'Projects', 'Logs Sinks Get']
- ['projects_logs-sinks-list.md', 'Projects', 'Logs Sinks List']
- ['projects_logs-sinks-update.md', 'Projects', 'Logs Sinks Update']

theme: readthedocs

copyright: Copyright &copy; 2015, `Sebastian Thiel`

