site_name: Recommender v1.0.14+20200704
site_url: http://byron.github.io/google-apis-rs/google-recommender1_beta1-cli
site_description: A complete library to interact with Recommender (protocol v1beta1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/recommender1_beta1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['projects_locations-insight-types-insights-get.md', 'Projects', 'Locations Insight Types Insights Get']
- ['projects_locations-insight-types-insights-list.md', 'Projects', 'Locations Insight Types Insights List']
- ['projects_locations-insight-types-insights-mark-accepted.md', 'Projects', 'Locations Insight Types Insights Mark Accepted']
- ['projects_locations-recommenders-recommendations-get.md', 'Projects', 'Locations Recommenders Recommendations Get']
- ['projects_locations-recommenders-recommendations-list.md', 'Projects', 'Locations Recommenders Recommendations List']
- ['projects_locations-recommenders-recommendations-mark-claimed.md', 'Projects', 'Locations Recommenders Recommendations Mark Claimed']
- ['projects_locations-recommenders-recommendations-mark-failed.md', 'Projects', 'Locations Recommenders Recommendations Mark Failed']
- ['projects_locations-recommenders-recommendations-mark-succeeded.md', 'Projects', 'Locations Recommenders Recommendations Mark Succeeded']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

