site_name: Identity Toolkit v0.3.2+20150710
site_url: http://byron.github.io/google-apis-rs/google-identitytoolkit3-cli
site_description: Write integrating applications with bcore

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/identitytoolkit3-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['relyingparty_create-auth-uri.md', 'Relyingparty', 'Create Auth Uri']
- ['relyingparty_delete-account.md', 'Relyingparty', 'Delete Account']
- ['relyingparty_download-account.md', 'Relyingparty', 'Download Account']
- ['relyingparty_get-account-info.md', 'Relyingparty', 'Get Account Info']
- ['relyingparty_get-oob-confirmation-code.md', 'Relyingparty', 'Get Oob Confirmation Code']
- ['relyingparty_get-public-keys.md', 'Relyingparty', 'Get Public Keys']
- ['relyingparty_get-recaptcha-param.md', 'Relyingparty', 'Get Recaptcha Param']
- ['relyingparty_reset-password.md', 'Relyingparty', 'Reset Password']
- ['relyingparty_set-account-info.md', 'Relyingparty', 'Set Account Info']
- ['relyingparty_upload-account.md', 'Relyingparty', 'Upload Account']
- ['relyingparty_verify-assertion.md', 'Relyingparty', 'Verify Assertion']
- ['relyingparty_verify-password.md', 'Relyingparty', 'Verify Password']

theme: readthedocs

copyright: Copyright &copy; 2015, `Sebastian Thiel`

