site_name: translate v0.3.3+20160217
site_url: http://byron.github.io/google-apis-rs/google-translate2-cli
site_description: Write integrating applications with bcore

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/translate2-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['detections_list.md', 'Detections', 'List']
- ['languages_list.md', 'Languages', 'List']
- ['translations_list.md', 'Translations', 'List']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

