site_name: replicapoolupdater v0.3.1+20150326
site_url: http://byron.github.io/google-apis-rs/google-replicapoolupdater1_beta1-cli
site_description: Write integrating applications with bcore

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/replicapoolupdater1_beta1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['rolling-updates_cancel.md', 'Rolling Updates', 'Cancel']
- ['rolling-updates_get.md', 'Rolling Updates', 'Get']
- ['rolling-updates_insert.md', 'Rolling Updates', 'Insert']
- ['rolling-updates_list.md', 'Rolling Updates', 'List']
- ['rolling-updates_list-instance-updates.md', 'Rolling Updates', 'List Instance Updates']
- ['rolling-updates_pause.md', 'Rolling Updates', 'Pause']
- ['rolling-updates_resume.md', 'Rolling Updates', 'Resume']
- ['rolling-updates_rollback.md', 'Rolling Updates', 'Rollback']
- ['zone-operations_get.md', 'Zone Operations', 'Get']

theme: readthedocs

copyright: Copyright &copy; 2015, `Sebastian Thiel`

