site_name: Groups Migration v0.3.0+20140416
site_url: http://byron.github.io/google-apis-rs/google-groupsmigration1-cli
site_description: Write integrating applications with bcore

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/groupsmigration1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['archive_insert.md', 'Archive', 'Insert']

theme: readthedocs

copyright: Copyright &copy; 2015, `Sebastian Thiel`

