site_name: YouTube v0.0.1+20150327
site_url: http://byron.github.io/google-apis-rs/google-youtube3-cli
site_description: Write integrating applications with bcore

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/youtube3-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['activities_insert.md', 'Activities', 'Insert']
- ['activities_list.md', 'Activities', 'List']
- ['captions_delete.md', 'Captions', 'Delete']
- ['captions_download.md', 'Captions', 'Download']
- ['captions_insert.md', 'Captions', 'Insert']
- ['captions_list.md', 'Captions', 'List']
- ['captions_update.md', 'Captions', 'Update']
- ['channel-banners_insert.md', 'Channel Banners', 'Insert']
- ['channel-sections_delete.md', 'Channel Sections', 'Delete']
- ['channel-sections_insert.md', 'Channel Sections', 'Insert']
- ['channel-sections_list.md', 'Channel Sections', 'List']
- ['channel-sections_update.md', 'Channel Sections', 'Update']
- ['channels_list.md', 'Channels', 'List']
- ['channels_update.md', 'Channels', 'Update']
- ['guide-categories_list.md', 'Guide Categories', 'List']
- ['i18n-languages_list.md', 'I18n Languages', 'List']
- ['i18n-regions_list.md', 'I18n Regions', 'List']
- ['live-broadcasts_bind.md', 'Live Broadcasts', 'Bind']
- ['live-broadcasts_control.md', 'Live Broadcasts', 'Control']
- ['live-broadcasts_delete.md', 'Live Broadcasts', 'Delete']
- ['live-broadcasts_insert.md', 'Live Broadcasts', 'Insert']
- ['live-broadcasts_list.md', 'Live Broadcasts', 'List']
- ['live-broadcasts_transition.md', 'Live Broadcasts', 'Transition']
- ['live-broadcasts_update.md', 'Live Broadcasts', 'Update']
- ['live-streams_delete.md', 'Live Streams', 'Delete']
- ['live-streams_insert.md', 'Live Streams', 'Insert']
- ['live-streams_list.md', 'Live Streams', 'List']
- ['live-streams_update.md', 'Live Streams', 'Update']
- ['playlist-items_delete.md', 'Playlist Items', 'Delete']
- ['playlist-items_insert.md', 'Playlist Items', 'Insert']
- ['playlist-items_list.md', 'Playlist Items', 'List']
- ['playlist-items_update.md', 'Playlist Items', 'Update']
- ['playlists_delete.md', 'Playlists', 'Delete']
- ['playlists_insert.md', 'Playlists', 'Insert']
- ['playlists_list.md', 'Playlists', 'List']
- ['playlists_update.md', 'Playlists', 'Update']
- ['search_list.md', 'Search', 'List']
- ['subscriptions_delete.md', 'Subscriptions', 'Delete']
- ['subscriptions_insert.md', 'Subscriptions', 'Insert']
- ['subscriptions_list.md', 'Subscriptions', 'List']
- ['thumbnails_set.md', 'Thumbnails', 'Set']
- ['video-categories_list.md', 'Video Categories', 'List']
- ['videos_delete.md', 'Videos', 'Delete']
- ['videos_get-rating.md', 'Videos', 'Get Rating']
- ['videos_insert.md', 'Videos', 'Insert']
- ['videos_list.md', 'Videos', 'List']
- ['videos_rate.md', 'Videos', 'Rate']
- ['videos_update.md', 'Videos', 'Update']
- ['watermarks_set.md', 'Watermarks', 'Set']
- ['watermarks_unset.md', 'Watermarks', 'Unset']

theme: readthedocs

copyright: Copyright &copy; 2015, `Sebastian Thiel`

