site_name: consumersurveys v0.3.4+20160405
site_url: http://byron.github.io/google-apis-rs/google-consumersurveys2-cli
site_description: Write integrating applications with bcore

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/consumersurveys2-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['results_get.md', 'Results', 'Get']
- ['surveys_get.md', 'Surveys', 'Get']
- ['surveys_insert.md', 'Surveys', 'Insert']
- ['surveys_list.md', 'Surveys', 'List']
- ['surveys_start.md', 'Surveys', 'Start']
- ['surveys_stop.md', 'Surveys', 'Stop']
- ['surveys_update.md', 'Surveys', 'Update']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

