site_name: Service User v1.0.6+20170916
site_url: http://byron.github.io/google-apis-rs/google-serviceuser1-cli
site_description: A complete library to interact with Service User (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/serviceuser1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['projects_services-disable.md', 'Projects', 'Services Disable']
- ['projects_services-enable.md', 'Projects', 'Services Enable']
- ['projects_services-list.md', 'Projects', 'Services List']
- ['services_search.md', 'Services', 'Search']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

