site_name: WebSecurityScanner v1.0.8+20190629
site_url: http://byron.github.io/google-apis-rs/google-websecurityscanner1-cli
site_description: A complete library to interact with WebSecurityScanner (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/websecurityscanner1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

