site_name: pubsub v0.2.0+20150326
site_url: http://byron.github.io/google-apis-rs/google-pubsub1_beta2-cli
site_description: Write integrating applications with bcore

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/pubsub1_beta2-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['projects_subscriptions-acknowledge.md', 'Projects', 'Subscriptions Acknowledge']
- ['projects_subscriptions-create.md', 'Projects', 'Subscriptions Create']
- ['projects_subscriptions-delete.md', 'Projects', 'Subscriptions Delete']
- ['projects_subscriptions-get.md', 'Projects', 'Subscriptions Get']
- ['projects_subscriptions-list.md', 'Projects', 'Subscriptions List']
- ['projects_subscriptions-modify-ack-deadline.md', 'Projects', 'Subscriptions Modify Ack Deadline']
- ['projects_subscriptions-modify-push-config.md', 'Projects', 'Subscriptions Modify Push Config']
- ['projects_subscriptions-pull.md', 'Projects', 'Subscriptions Pull']
- ['projects_topics-create.md', 'Projects', 'Topics Create']
- ['projects_topics-delete.md', 'Projects', 'Topics Delete']
- ['projects_topics-get.md', 'Projects', 'Topics Get']
- ['projects_topics-list.md', 'Projects', 'Topics List']
- ['projects_topics-publish.md', 'Projects', 'Topics Publish']
- ['projects_topics-subscriptions-list.md', 'Projects', 'Topics Subscriptions List']

theme: readthedocs

copyright: Copyright &copy; 2015, `Sebastian Thiel`

