site_name: safebrowsing v1.0.6+20170509
site_url: http://byron.github.io/google-apis-rs/google-safebrowsing4-cli
site_description: A complete library to interact with safebrowsing (protocol v4)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/safebrowsing4-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['encoded-full-hashes_get.md', 'Encoded Full Hashes', 'Get']
- ['encoded-updates_get.md', 'Encoded Updates', 'Get']
- ['full-hashes_find.md', 'Full Hashes', 'Find']
- ['threat-list-updates_fetch.md', 'Threat List Updates', 'Fetch']
- ['threat-lists_list.md', 'Threat Lists', 'List']
- ['threat-matches_find.md', 'Threat Matches', 'Find']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

