site_name: genomics v0.1.0+20150326
site_url: http://byron.github.io/google-apis-rs/google-genomics1_beta2-cli
site_description: Write integrating applications with bcore

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/genomics1_beta2-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['annotation-sets_create.md', 'Annotation Sets', 'Create']
- ['annotation-sets_delete.md', 'Annotation Sets', 'Delete']
- ['annotation-sets_get.md', 'Annotation Sets', 'Get']
- ['annotation-sets_patch.md', 'Annotation Sets', 'Patch']
- ['annotation-sets_search.md', 'Annotation Sets', 'Search']
- ['annotation-sets_update.md', 'Annotation Sets', 'Update']
- ['annotations_batch-create.md', 'Annotations', 'Batch Create']
- ['annotations_create.md', 'Annotations', 'Create']
- ['annotations_delete.md', 'Annotations', 'Delete']
- ['annotations_get.md', 'Annotations', 'Get']
- ['annotations_patch.md', 'Annotations', 'Patch']
- ['annotations_search.md', 'Annotations', 'Search']
- ['annotations_update.md', 'Annotations', 'Update']
- ['callsets_create.md', 'Callsets', 'Create']
- ['callsets_delete.md', 'Callsets', 'Delete']
- ['callsets_get.md', 'Callsets', 'Get']
- ['callsets_patch.md', 'Callsets', 'Patch']
- ['callsets_search.md', 'Callsets', 'Search']
- ['callsets_update.md', 'Callsets', 'Update']
- ['datasets_create.md', 'Datasets', 'Create']
- ['datasets_delete.md', 'Datasets', 'Delete']
- ['datasets_get.md', 'Datasets', 'Get']
- ['datasets_list.md', 'Datasets', 'List']
- ['datasets_patch.md', 'Datasets', 'Patch']
- ['datasets_undelete.md', 'Datasets', 'Undelete']
- ['datasets_update.md', 'Datasets', 'Update']
- ['experimental_jobs-create.md', 'Experimental', 'Jobs Create']
- ['jobs_cancel.md', 'Jobs', 'Cancel']
- ['jobs_get.md', 'Jobs', 'Get']
- ['jobs_search.md', 'Jobs', 'Search']
- ['readgroupsets_align.md', 'Readgroupsets', 'Align']
- ['readgroupsets_call.md', 'Readgroupsets', 'Call']
- ['readgroupsets_coveragebuckets-list.md', 'Readgroupsets', 'Coveragebuckets List']
- ['readgroupsets_delete.md', 'Readgroupsets', 'Delete']
- ['readgroupsets_export.md', 'Readgroupsets', 'Export']
- ['readgroupsets_get.md', 'Readgroupsets', 'Get']
- ['readgroupsets_import.md', 'Readgroupsets', 'Import']
- ['readgroupsets_patch.md', 'Readgroupsets', 'Patch']
- ['readgroupsets_search.md', 'Readgroupsets', 'Search']
- ['readgroupsets_update.md', 'Readgroupsets', 'Update']
- ['reads_search.md', 'Reads', 'Search']
- ['references_bases-list.md', 'References', 'Bases List']
- ['references_get.md', 'References', 'Get']
- ['references_search.md', 'References', 'Search']
- ['referencesets_get.md', 'Referencesets', 'Get']
- ['referencesets_search.md', 'Referencesets', 'Search']
- ['streaming-readstore_streamreads.md', 'Streaming Readstore', 'Streamreads']
- ['variants_create.md', 'Variants', 'Create']
- ['variants_delete.md', 'Variants', 'Delete']
- ['variants_get.md', 'Variants', 'Get']
- ['variants_search.md', 'Variants', 'Search']
- ['variants_update.md', 'Variants', 'Update']
- ['variantsets_delete.md', 'Variantsets', 'Delete']
- ['variantsets_export.md', 'Variantsets', 'Export']
- ['variantsets_get.md', 'Variantsets', 'Get']
- ['variantsets_import-variants.md', 'Variantsets', 'Import Variants']
- ['variantsets_merge-variants.md', 'Variantsets', 'Merge Variants']
- ['variantsets_patch.md', 'Variantsets', 'Patch']
- ['variantsets_search.md', 'Variantsets', 'Search']
- ['variantsets_update.md', 'Variantsets', 'Update']

theme: readthedocs

copyright: Copyright &copy; 2015, `Sebastian Thiel`

