site_name: Cloud Resource Manager v0.3.6+20160316
site_url: http://byron.github.io/google-apis-rs/google-cloudresourcemanager1-cli
site_description: Write integrating applications with bcore

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/cloudresourcemanager1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['projects_delete.md', 'Projects', 'Delete']
- ['projects_get.md', 'Projects', 'Get']
- ['projects_get-iam-policy.md', 'Projects', 'Get Iam Policy']
- ['projects_list.md', 'Projects', 'List']
- ['projects_set-iam-policy.md', 'Projects', 'Set Iam Policy']
- ['projects_test-iam-permissions.md', 'Projects', 'Test Iam Permissions']
- ['projects_undelete.md', 'Projects', 'Undelete']
- ['projects_update.md', 'Projects', 'Update']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

