site_name: pagespeedonline v0.3.5+20160306
site_url: http://byron.github.io/google-apis-rs/google-pagespeedonline2-cli
site_description: Write integrating applications with bcore

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/pagespeedonline2-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['pagespeedapi_runpagespeed.md', 'Pagespeedapi', 'Runpagespeed']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

