site_name: script v0.3.3+20150922
site_url: http://byron.github.io/google-apis-rs/google-script1-cli
site_description: Write integrating applications with bcore

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/script1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['scripts_run.md', 'Scripts', 'Run']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

