site_name: genomics v0.3.0+20150615
site_url: http://byron.github.io/google-apis-rs/google-genomics1-cli
site_description: Write integrating applications with bcore

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/genomics1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']

theme: readthedocs

copyright: Copyright &copy; 2015, `Sebastian Thiel`

