site_name: cloudtrace v0.3.6+20151207
site_url: http://byron.github.io/google-apis-rs/google-cloudtrace1-cli
site_description: Write integrating applications with bcore

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/cloudtrace1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['projects_patch-traces.md', 'Projects', 'Patch Traces']
- ['projects_traces-get.md', 'Projects', 'Traces Get']
- ['projects_traces-list.md', 'Projects', 'Traces List']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

