name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2
      - name: Run clippy
        run: |
          cargo clippy -- -D warnings
  build-and-test:
    runs-on: ubuntu-latest
    env:
      TRAVIS: true # emulate CI, some code depends on it to do less work
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: |
          source ~/.profile
          make test-gen
          make gen-all-cli cargo-api ARGS=test
          make cargo-api ARGS='check --no-default-features'
          make cargo-api ARGS=doc
          make docs-all
          cargo test
