name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup pyenv
      uses: "gabrielfalcao/pyenv-action@v5"
      with:
        default: 2.7.17
    - name: Run tests
      run: |
        source ~/.profile
        make test-gen
        make gen-all-cli cargo-api ARGS=test
        make cargo-api ARGS=doc
        cargo test
